import os

Import("baseEnvironment")

env = baseEnvironment.Clone()

env.Tool("swig")
env.Append(ENV = os.environ)

env.Append(CPPPATH = ["../libwendy/include"])
env.Append(LIBPATH = ["../libwendy/lib"])
env.Append(LIBS = ["wendy", "python27"])
env.Append(SWIGFLAGS = ["-c++"])
env.Append(SWIGFLAGS = ["-python"])
env.Append(SWIGFLAGS = ["-Ilibwendy/include"])
env["SHLIBPREFIX"] = "" # remove the leading 'lib' from output library filename
if os.name == "posix":
	# TODO: remove hard-coded python path
	env.Append(CPPPATH = ["/usr/include/python2.7"])
else:
	env["SHLIBSUFFIX"] = ".pyd" # enforce .pyd instead of .dll
	env.Append(CPPPATH = ["$BINARYDEPS/python27/include"])
	env.Append(LIBPATH = ["$BINARYDEPS/python27/libs"])
if env["CC"] == "cl":
	env.Append(CPPFLAGS = ["/EHsc"])
env.SharedLibrary("lib/_pywendy", env.Glob("src/*.i"))

distItems = []
Return("distItems")

