import os

Import("baseEnvironment")

env = baseEnvironment.Clone()

env.Append(CPPPATH = ["src", "../libwendy/src"])
env.Append(LIBPATH = ["../$BUILDDIR/bin"])
env.Append(LIBS = ["cJSON", "wendy"])

if os.name == "nt":
	env.Append(CPPPATH = ["../dependencies/dokan/dokan"])
	env.Append(LIBPATH = ["../dependencies/dokan-bin"])
	env.Append(CPPDEFINES = ["UNICODE", "_UNICODE"])
	env.Append(LIBS = ["psapi", "dokan"])
else:
	env.ParseConfig("pkg-config --cflags --libs fuse")
	env.Append(CPPDEFINES = "FUSE_USE_VERSION=28")

sources = env.Glob("src/*.cpp")
objects = []
for file in sources:
	objects += [env.SharedObject("../$BUILDDIR/obj/wendyfs/" + os.path.splitext(str(file))[0], file)]

env.Program("../$BUILDDIR/bin/wendyfs", objects)
